### ISSUE TITLE
Module Manager patching compatibility

### ISSUE THREAD

**Issue by PhineasFreak** [MOARdV/DistantObject#34]
Currently the only ways to add configs for the planetary bodies are:
- Remove the config shipped with DOE and replace it with a selected one.
- Create a new config with the same structure and place it somewhere under the GameData folder.

The second option works fine but since it adds new flare definitions "on top" of the DOE (and custom) ones it is possible that duplicates may occur. I do not know if it is good or bad (probably bad) to have duplicate flare definitions for a single body but i can assume that the one that loads last will have the priority over the others.

To conclude, i am asking if for the next version(s) a new config loading system could be implemented. Since it will be modified once there will be no problems with MM rebuilding it's database on each KSP launch.

**Comment by MOARdV** [comment]
I'm not sure why you believe the current method doesn't work with MM.  Each body's color is contained in a node named `CelestialBodyColor`, and each is uniquely named, so can't MM use

```
@CelestialBodyColor[Moho]
{
   ... some change ...
}
```
?

As for duplicates / extras - any `CelestialBodyColor` that does not have a corresponding CelestialBody with the same name is ignored.  If multiple `CelestialBodyColor` nodes use the same name, only the first one will be used (extras are ignored), where 'first one' is whichever entry KSP lists first in the game database.

**Comment by PhineasFreak** [comment]
OK, so i managed to delete the flare definitions (needed some more MM patching care than i thought):

```
!CelestialBodyColor[*],*:BEFORE[MyMod]
```

But it is not possible to add new ones. If i try to define a MM pass it will fail:

```
CelestialBodyColor:FOR[MyMod]
{
.
.
.
}
```

They exist as MM includes them in the cache but they are not used (DOE uses the fallback white color). It will not happen if the "FOR[MyMod]" pass is not included but then they are removed during the first "cleanup" pass.

**Comment by MOARdV** [comment]
> They exist as MM includes them in the cache but they are not used (DOE uses the fallback white color). It will not happen if the "FOR[MyMod]" pass is not included but then they are removed during the first "cleanup" pass.

If they're in the cache (and they have the right `name` and `color` fields), then it sounds like DOE isn't seeing a match between the CelestialBody name in FlightGlobals.Bodies and the name listed in the CelestialBodyColor `name` field.  The names must match exactly, and any modifications of the FlightGlobals database needs to take place before DOE's Awake method is called - that's where DOE sets up its flares.

One other question - are you trying this in 1.1.3, or 1.2 pre-release?  If it's the latter, I'd wait until sarbian releases an official MM build - I don't want to spend time chasing what may be a bug in an incorrectly-updated unofficial build of MM.  If it's 1.1.3, please zip up the MM cache file and log files, and I'll take a look at them.

**Comment by PhineasFreak** [comment]
Then Kopernicus might the be culprit, since the RSS bodies are created as "copies" (templates) of the stock ones so when DOE loads the configs the bodies might not have been active yet.

Anyway, this proved not to be an easy thing to "debug" and it is getting off-topic now. You can close it if you want and i will use the default loading system.
